# Generated by Django 5.2.5 on 2025-09-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="name",
            new_name="title",
        ),
    ]
